package com.jxjr.m.dbcode;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.jxjr.m.pojo.BaseInfoObjectPOJO;
import com.jxjr.m.pojo.BaseInfoObjectPOJODao;
import com.jxjr.m.pojo.BillCodePOJO;
import com.jxjr.m.pojo.BillCodePOJODao;
import com.jxjr.m.pojo.LogInfoPOJO;
import com.jxjr.m.pojo.LogInfoPOJODao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig baseInfoObjectPOJODaoConfig;
	private final DaoConfig billCodePOJODaoConfig;
	// private final DaoConfig sBInfoObjectPOJODaoConfig;
	// private final DaoConfig lineInfoObjectPOJODaoConfig;
	// private final DaoConfig taskObjectPOJODaoConfig;
	// private final DaoConfig rhDysInfoPOJODaoConfig;
	// private final DaoConfig dwxOrDysYCInfoPOJODaoConfig;
	// private final DaoConfig ycWxInfoPOJODaoConfig;
	// private final DaoConfig ycYsInfoPOJODaoConfig;
	// private final DaoConfig rhYsInfoPOJODaoConfig;
	// private final DaoConfig treeNodeBeanPOJODaoConfig;
	// private final DaoConfig phoneTaskObjectPOJODaoConfig;
	//private final DaoConfig logInfoPOJODaoConfig;

	private final BaseInfoObjectPOJODao baseInfoObjectPOJODao;
	private final BillCodePOJODao billCodePOJODao;
	// private final SBInfoObjectPOJODao sBInfoObjectPOJODao;
	// private final LineInfoObjectPOJODao lineInfoObjectPOJODao;
	// private final TaskObjectPOJODao taskObjectPOJODao;
	// private final RhDysInfoPOJODao rhDysInfoPOJODao;
	// private final DwxOrDysYCInfoPOJODao dwxOrDysYCInfoPOJODao;
	// private final YcWxInfoPOJODao ycWxInfoPOJODao;
	// private final YcYsInfoPOJODao ycYsInfoPOJODao;
	// private final RhYsInfoPOJODao rhYsInfoPOJODao;
	// private final TreeNodeBeanPOJODao treeNodeBeanPOJODao;
	// private final PhoneTaskObjectPOJODao phoneTaskObjectPOJODao;
	//private final LogInfoPOJODao logInfoPOJODao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		baseInfoObjectPOJODaoConfig = daoConfigMap.get(BaseInfoObjectPOJODao.class).clone();
		baseInfoObjectPOJODaoConfig.initIdentityScope(type);
		billCodePOJODaoConfig = daoConfigMap.get(BillCodePOJODao.class).clone();
		billCodePOJODaoConfig.initIdentityScope(type);

		// sBInfoObjectPOJODaoConfig =
		// daoConfigMap.get(SBInfoObjectPOJODao.class).clone();
		// sBInfoObjectPOJODaoConfig.initIdentityScope(type);
		//
		// lineInfoObjectPOJODaoConfig =
		// daoConfigMap.get(LineInfoObjectPOJODao.class).clone();
		// lineInfoObjectPOJODaoConfig.initIdentityScope(type);
		//
		// taskObjectPOJODaoConfig = daoConfigMap.get(TaskObjectPOJODao.class).clone();
		// taskObjectPOJODaoConfig.initIdentityScope(type);
		//
		// rhDysInfoPOJODaoConfig = daoConfigMap.get(RhDysInfoPOJODao.class).clone();
		// rhDysInfoPOJODaoConfig.initIdentityScope(type);
		//
		// dwxOrDysYCInfoPOJODaoConfig =
		// daoConfigMap.get(DwxOrDysYCInfoPOJODao.class).clone();
		// dwxOrDysYCInfoPOJODaoConfig.initIdentityScope(type);
		//
		// ycWxInfoPOJODaoConfig = daoConfigMap.get(YcWxInfoPOJODao.class).clone();
		// ycWxInfoPOJODaoConfig.initIdentityScope(type);
		//
		// ycYsInfoPOJODaoConfig = daoConfigMap.get(YcYsInfoPOJODao.class).clone();
		// ycYsInfoPOJODaoConfig.initIdentityScope(type);
		//
		// rhYsInfoPOJODaoConfig = daoConfigMap.get(RhYsInfoPOJODao.class).clone();
		// rhYsInfoPOJODaoConfig.initIdentityScope(type);
		//
		// treeNodeBeanPOJODaoConfig =
		// daoConfigMap.get(TreeNodeBeanPOJODao.class).clone();
		// treeNodeBeanPOJODaoConfig.initIdentityScope(type);
		//
		// phoneTaskObjectPOJODaoConfig =
		// daoConfigMap.get(PhoneTaskObjectPOJODao.class).clone();
		// phoneTaskObjectPOJODaoConfig.initIdentityScope(type);
		//
		/*logInfoPOJODaoConfig = daoConfigMap.get(LogInfoPOJODao.class).clone();
		logInfoPOJODaoConfig.initIdentityScope(type);*/

		baseInfoObjectPOJODao = new BaseInfoObjectPOJODao(baseInfoObjectPOJODaoConfig, this);
		billCodePOJODao = new BillCodePOJODao(billCodePOJODaoConfig, this);
		// sBInfoObjectPOJODao = new SBInfoObjectPOJODao(sBInfoObjectPOJODaoConfig,
		// this);
		// lineInfoObjectPOJODao = new
		// LineInfoObjectPOJODao(lineInfoObjectPOJODaoConfig, this);
		// taskObjectPOJODao = new TaskObjectPOJODao(taskObjectPOJODaoConfig, this);
		// rhDysInfoPOJODao = new RhDysInfoPOJODao(rhDysInfoPOJODaoConfig, this);
		// dwxOrDysYCInfoPOJODao = new
		// DwxOrDysYCInfoPOJODao(dwxOrDysYCInfoPOJODaoConfig, this);
		// ycWxInfoPOJODao = new YcWxInfoPOJODao(ycWxInfoPOJODaoConfig, this);
		// ycYsInfoPOJODao = new YcYsInfoPOJODao(ycYsInfoPOJODaoConfig, this);
		// rhYsInfoPOJODao = new RhYsInfoPOJODao(rhYsInfoPOJODaoConfig, this);
		// treeNodeBeanPOJODao = new TreeNodeBeanPOJODao(treeNodeBeanPOJODaoConfig,
		// this);
		// phoneTaskObjectPOJODao = new
		// PhoneTaskObjectPOJODao(phoneTaskObjectPOJODaoConfig, this);
		//logInfoPOJODao = new LogInfoPOJODao(logInfoPOJODaoConfig, this);

		registerDao(BaseInfoObjectPOJO.class, baseInfoObjectPOJODao);
		//
		// registerDao(SBInfoObjectPOJO.class, sBInfoObjectPOJODao);
		// registerDao(LineInfoObjectPOJO.class, lineInfoObjectPOJODao);
		// registerDao(TaskObjectPOJO.class, taskObjectPOJODao);
		// registerDao(RhDysInfoPOJO.class, rhDysInfoPOJODao);
		// registerDao(DwxOrDysYCInfoPOJO.class, dwxOrDysYCInfoPOJODao);
		// registerDao(YcWxInfoPOJO.class, ycWxInfoPOJODao);
		// registerDao(YcYsInfoPOJO.class, ycYsInfoPOJODao);
		// registerDao(RhYsInfoPOJO.class, rhYsInfoPOJODao);
		// registerDao(TreeNodeBeanPOJO.class, treeNodeBeanPOJODao);
		// registerDao(PhoneTaskObjectPOJO.class, phoneTaskObjectPOJODao);
		registerDao(BillCodePOJO.class, billCodePOJODao);
		//registerDao(LogInfoPOJO.class, logInfoPOJODao);
	}

	public void clear() {
		baseInfoObjectPOJODaoConfig.getIdentityScope().clear();
		billCodePOJODaoConfig.getIdentityScope().clear();
		// sBInfoObjectPOJODaoConfig.getIdentityScope().clear();
		// lineInfoObjectPOJODaoConfig.getIdentityScope().clear();
		// taskObjectPOJODaoConfig.getIdentityScope().clear();
		// rhDysInfoPOJODaoConfig.getIdentityScope().clear();
		// dwxOrDysYCInfoPOJODaoConfig.getIdentityScope().clear();
		// ycWxInfoPOJODaoConfig.getIdentityScope().clear();
		// ycYsInfoPOJODaoConfig.getIdentityScope().clear();
		// rhYsInfoPOJODaoConfig.getIdentityScope().clear();
		// treeNodeBeanPOJODaoConfig.getIdentityScope().clear();
		// phoneTaskObjectPOJODaoConfig.getIdentityScope().clear();
		// logInfoPOJODaoConfig.getIdentityScope().clear();
	}

	public BaseInfoObjectPOJODao getBaseInfoObjectPOJODao() {
		return baseInfoObjectPOJODao;
	}

	public BillCodePOJODao getBillCodePOJODao() {
		return billCodePOJODao;
	}
	// public SBInfoObjectPOJODao getSBInfoObjectPOJODao() {
	// return sBInfoObjectPOJODao;
	// }
	//
	// public LineInfoObjectPOJODao getLineInfoObjectPOJODao() {
	// return lineInfoObjectPOJODao;
	// }
	//
	// public TaskObjectPOJODao getTaskObjectPOJODao() {
	// return taskObjectPOJODao;
	// }
	//
	// public RhDysInfoPOJODao getRhDysInfoPOJODao() {
	// return rhDysInfoPOJODao;
	// }
	//
	// public DwxOrDysYCInfoPOJODao getDwxOrDysYCInfoPOJODao() {
	// return dwxOrDysYCInfoPOJODao;
	// }
	//
	// public YcWxInfoPOJODao getYcWxInfoPOJODao() {
	// return ycWxInfoPOJODao;
	// }
	//
	// public YcYsInfoPOJODao getYcYsInfoPOJODao() {
	// return ycYsInfoPOJODao;
	// }
	//
	// public RhYsInfoPOJODao getRhYsInfoPOJODao() {
	// return rhYsInfoPOJODao;
	// }
	//
	// public TreeNodeBeanPOJODao getTreeNodeBeanPOJODao() {
	// return treeNodeBeanPOJODao;
	// }
	//
	// public PhoneTaskObjectPOJODao getPhoneTaskObjectPOJODao() {
	// return phoneTaskObjectPOJODao;
	// }

	/*public LogInfoPOJODao getLogInfoPOJODao() {
		return logInfoPOJODao;
	}*/

}
