package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * JrManufactureRecBill generated by hbm2java
 */

public class JrPdaGxhbYgentry implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private int parentid;
	private String fid;
	private String fentryid;
	private String fnumber;
	private String fbzid;
	private String fbznumber;
	private String fbzname;	
	private String fygid;
	private String fygnumber;
	private String fygname;	
	private BigDecimal  fygxs;

	
	public JrPdaGxhbYgentry() {
	}

	public JrPdaGxhbYgentry(int id) {
		this.id = id;
	}

	public JrPdaGxhbYgentry(int id, int parentid, String fid, String fentryid,
			String fnumber, String fbzid, String fbznumber, String fbzname,
			String fygid, String fygnumber, String fygname, BigDecimal fygxs) {
		super();
		this.id = id;
		this.parentid = parentid;
		this.fid = fid;
		this.fentryid = fentryid;
		this.fnumber = fnumber;
		this.fbzid = fbzid;
		this.fbznumber = fbznumber;
		this.fbzname = fbzname;
		this.fygid = fygid;
		this.fygnumber = fygnumber;
		this.fygname = fygname;
		this.fygxs = fygxs;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getParentid() {
		return parentid;
	}

	public void setParentid(int parentid) {
		this.parentid = parentid;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFentryid() {
		return fentryid;
	}

	public void setFentryid(String fentryid) {
		this.fentryid = fentryid;
	}

	public String getFnumber() {
		return fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFbzid() {
		return fbzid;
	}

	public void setFbzid(String fbzid) {
		this.fbzid = fbzid;
	}

	public String getFbznumber() {
		return fbznumber;
	}

	public void setFbznumber(String fbznumber) {
		this.fbznumber = fbznumber;
	}

	public String getFbzname() {
		return fbzname;
	}

	public void setFbzname(String fbzname) {
		this.fbzname = fbzname;
	}

	public String getFygid() {
		return fygid;
	}

	public void setFygid(String fygid) {
		this.fygid = fygid;
	}

	public String getFygnumber() {
		return fygnumber;
	}

	public void setFygnumber(String fygnumber) {
		this.fygnumber = fygnumber;
	}

	public String getFygname() {
		return fygname;
	}

	public void setFygname(String fygname) {
		this.fygname = fygname;
	}

	public BigDecimal getFygxs() {
		return fygxs;
	}

	public void setFygxs(BigDecimal fygxs) {
		this.fygxs = fygxs;
	}

	
	@Override  
    public Object clone() {  
		JrPdaGxhbYgentry obj = null;  
        try{  
        	obj = (JrPdaGxhbYgentry)super.clone();  
        }catch(CloneNotSupportedException e) {  
            e.printStackTrace();  
        }  
        return obj;  
    }  
	
}
