package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * JrSaleIssueBill generated by hbm2java
 */
public class JrPdaScllbill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String fid;
	private String fnumber;
	private Date fbizdate;
	private String fbiztype;
	private String fylqdId;
	private String fylqdNo;
	private String fdeptId;
	private String fdeptNumber;
	private String fdeptName;
	private Date fdate;
	private BigDecimal ftotalqty;
	private String fmemo;
	private String fbasestatus;
	private String fcreateuserid;
	private String fcreateusername;
	private String forgid;


	
	public JrPdaScllbill() {
	}

	public JrPdaScllbill(int id) {
		this.id = id;
	}

	public JrPdaScllbill(int id, String fid, String fnumber, Date fbizdate,
			String fbiztype, String fylqdId, String fylqdNo, String fdeptId,
			String fdeptNumber, String fdeptName, Date fdate,
			BigDecimal ftotalqty, String fmemo, String fbasestatus,
			String fcreateuserid, String fcreateusername, String forgid) {
		super();
		this.id = id;
		this.fid = fid;
		this.fnumber = fnumber;
		this.fbizdate = fbizdate;
		this.fbiztype = fbiztype;
		this.fylqdId = fylqdId;
		this.fylqdNo = fylqdNo;
		this.fdeptId = fdeptId;
		this.fdeptNumber = fdeptNumber;
		this.fdeptName = fdeptName;
		this.fdate = fdate;
		this.ftotalqty = ftotalqty;
		this.fmemo = fmemo;
		this.fbasestatus = fbasestatus;
		this.fcreateuserid = fcreateuserid;
		this.fcreateusername = fcreateusername;
		this.forgid = forgid;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Date getFbizdate() {
		return fbizdate;
	}

	public void setFbizdate(Date fbizdate) {
		this.fbizdate = fbizdate;
	}

	public String getFbiztype() {
		return fbiztype;
	}

	public void setFbiztype(String fbiztype) {
		this.fbiztype = fbiztype;
	}

	public String getFylqdId() {
		return fylqdId;
	}

	public void setFylqdId(String fylqdId) {
		this.fylqdId = fylqdId;
	}

	public String getFylqdNo() {
		return fylqdNo;
	}

	public void setFylqdNo(String fylqdNo) {
		this.fylqdNo = fylqdNo;
	}

	public String getFdeptId() {
		return fdeptId;
	}

	public void setFdeptId(String fdeptId) {
		this.fdeptId = fdeptId;
	}

	public String getFdeptNumber() {
		return fdeptNumber;
	}

	public void setFdeptNumber(String fdeptNumber) {
		this.fdeptNumber = fdeptNumber;
	}

	public String getFdeptName() {
		return fdeptName;
	}

	public void setFdeptName(String fdeptName) {
		this.fdeptName = fdeptName;
	}

	public Date getFdate() {
		return fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	public BigDecimal getFtotalqty() {
		return ftotalqty;
	}

	public void setFtotalqty(BigDecimal ftotalqty) {
		this.ftotalqty = ftotalqty;
	}

	public String getFmemo() {
		return fmemo;
	}

	public void setFmemo(String fmemo) {
		this.fmemo = fmemo;
	}

	public String getFbasestatus() {
		return fbasestatus;
	}

	public void setFbasestatus(String fbasestatus) {
		this.fbasestatus = fbasestatus;
	}

	public String getFcreateuserid() {
		return fcreateuserid;
	}

	public void setFcreateuserid(String fcreateuserid) {
		this.fcreateuserid = fcreateuserid;
	}

	public String getFcreateusername() {
		return fcreateusername;
	}

	public void setFcreateusername(String fcreateusername) {
		this.fcreateusername = fcreateusername;
	}

	public String getForgid() {
		return forgid;
	}

	public void setForgid(String forgid) {
		this.forgid = forgid;
	}

	
	
}
