package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * JrManufactureRecBill generated by hbm2java
 */

public class JrPdaGxhbbill implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String fid;
	private String fnumber;
	private String fdeptId;
	private String fdeptNumber;
	private String fdeptName;
	private String fbzId;
	private String fbzNumber;
	private String fbzName;
	private String fempxx;
	private String frkdNo;
	private String frkdId;
	private String fjjdNo;
	private String fjjdId;
	private String fcreateuserid;
	private String fcreateusername;
	private String ftype;
	private String fmemo;
	private Date fdate;
	private Date fcwdate;

	
	public JrPdaGxhbbill() {
	}

	public JrPdaGxhbbill(int id) {
		this.id = id;
	}

	public JrPdaGxhbbill(int id, String fid, String fnumber, String fdeptId,
			String fdeptNumber, String fdeptName, String fbzId,
			String fbzNumber, String fbzName, String fempxx, String frkdNo,
			String frkdId, String fjjdNo, String fjjdId, String fcreateuserid,
			String fcreateusername, String ftype, String fmemo, Date fdate,Date fcwdate) {
		super();
		this.id = id;
		this.fid = fid;
		this.fnumber = fnumber;
		this.fdeptId = fdeptId;
		this.fdeptNumber = fdeptNumber;
		this.fdeptName = fdeptName;
		this.fbzId = fbzId;
		this.fbzNumber = fbzNumber;
		this.fbzName = fbzName;
		this.fempxx = fempxx;
		this.frkdNo = frkdNo;
		this.frkdId = frkdId;
		this.fjjdNo = fjjdNo;
		this.fjjdId = fjjdId;
		this.fcreateuserid = fcreateuserid;
		this.fcreateusername = fcreateusername;
		this.ftype = ftype;
		this.fmemo = fmemo;
		this.fdate = fdate;
		this.fcwdate = fcwdate;
	}

	public Date getFcwdate() {
		return fcwdate;
	}

	public void setFcwdate(Date fcwdate) {
		this.fcwdate = fcwdate;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdeptId() {
		return fdeptId;
	}

	public void setFdeptId(String fdeptId) {
		this.fdeptId = fdeptId;
	}

	public String getFdeptNumber() {
		return fdeptNumber;
	}

	public void setFdeptNumber(String fdeptNumber) {
		this.fdeptNumber = fdeptNumber;
	}

	public String getFdeptName() {
		return fdeptName;
	}

	public void setFdeptName(String fdeptName) {
		this.fdeptName = fdeptName;
	}

	public String getFbzId() {
		return fbzId;
	}

	public void setFbzId(String fbzId) {
		this.fbzId = fbzId;
	}

	public String getFbzNumber() {
		return fbzNumber;
	}

	public void setFbzNumber(String fbzNumber) {
		this.fbzNumber = fbzNumber;
	}

	public String getFbzName() {
		return fbzName;
	}

	public void setFbzName(String fbzName) {
		this.fbzName = fbzName;
	}

	public String getFempxx() {
		return fempxx;
	}

	public void setFempxx(String fempxx) {
		this.fempxx = fempxx;
	}

	public String getFrkdNo() {
		return frkdNo;
	}

	public void setFrkdNo(String frkdNo) {
		this.frkdNo = frkdNo;
	}

	public String getFrkdId() {
		return frkdId;
	}

	public void setFrkdId(String frkdId) {
		this.frkdId = frkdId;
	}

	public String getFjjdNo() {
		return fjjdNo;
	}

	public void setFjjdNo(String fjjdNo) {
		this.fjjdNo = fjjdNo;
	}

	public String getFjjdId() {
		return fjjdId;
	}

	public void setFjjdId(String fjjdId) {
		this.fjjdId = fjjdId;
	}

	public String getFcreateuserid() {
		return fcreateuserid;
	}

	public void setFcreateuserid(String fcreateuserid) {
		this.fcreateuserid = fcreateuserid;
	}

	public String getFcreateusername() {
		return fcreateusername;
	}

	public void setFcreateusername(String fcreateusername) {
		this.fcreateusername = fcreateusername;
	}

	public String getFtype() {
		return ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public String getFmemo() {
		return fmemo;
	}

	public void setFmemo(String fmemo) {
		this.fmemo = fmemo;
	}

	public Date getFdate() {
		return fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	
	
}
