package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * JrManufactureRecBillEntry generated by hbm2java
 */

public class JrPdaGxpgbillentry implements java.io.Serializable,Cloneable {


	private static final long serialVersionUID = 1L;
	private int id;
	private int parentid;
	private String fid;//单据内码
	private String fentryid;//单据分录内码
	private String fseq;
	private String fgxlzkNo;//工序流转卡no
	private String fgxlzkSeq;//工序流转卡行号
	private String fgxlzkId;
	private String fgxlzkentryId;
	private String fscddNo;
	private String fscddSeq;
	private String fscddId;
	private String fscddentryId;
	private String fmatId;
	private String fmatNumber;
	private String fmatName;
	private String fmatModel;
	private String fclxx;
	private String fjgxx;
	private String fgxId;
	private String fgxNumber;
	private String fgxName;
	private BigDecimal fqty;
	private String fisjj;
	private String fjjcjId;
	private String fjjcjNumber;
	private String fjjcjName;
	private String fisrk;
	private String frkckId;
	private String frkckNumber;
	private String frkckName;
	private String fistjgs;
	private String fsupId;
	private String fsupNumber;
	private String fsupName;
	private String ftm;
	private String fnote;

	public JrPdaGxpgbillentry() {
	}

	public JrPdaGxpgbillentry(int id) {
		this.id = id;
	}

	public JrPdaGxpgbillentry(int id, int parentid,String fid,
			String fentryid, String fseq,String fgxlzkNo, String fgxlzkSeq,
			String fgxlzkId, String fgxlzkentryId, String fscddNo,
			String fscddSeq, String fscddId, String fscddentryId, String fmatId,
			String fmatNumber, String fmatName,
			String fmatModel,String fclxx,String fjgxx,String fgxId,
			String fgxNumber,String fgxName,BigDecimal fqty,
			String fisjj,String fjjcjId,String fjjcjNumber,String fjjcjName,
			String fisrk,String frkckId
			,String frkckNumber,String frkckName,String fistjgs,String fsupId
			,String fsupNumber,String fsupName,String ftm,String fnote) {
		this.id = id;
		this.parentid=parentid;
		this.fid = fid;
		this.fentryid = fentryid;
		this.fseq = fseq;
		this.fgxlzkNo = fgxlzkNo;
		this.fgxlzkSeq = fgxlzkSeq;
		this.fgxlzkId = fgxlzkId;
		this.fgxlzkentryId = fgxlzkentryId;
		this.fscddNo = fscddNo;
		this.fscddSeq = fscddSeq;
		this.fscddId = fscddId;
		this.fscddentryId = fscddentryId;
		this.fmatId = fmatId;
		this.fmatNumber = fmatNumber;
		this.fmatName = fmatName;
		this.fmatModel = fmatModel;
		this.fclxx = fclxx;
		this.fjgxx = fjgxx;
		this.fgxId = fgxId;
		this.fgxNumber = fgxNumber;
		this.fgxName = fgxName;
		this.fqty = fqty;
		this.fisjj = fisjj;
		this.fjjcjId = fjjcjId;
		this.fjjcjNumber = fjjcjNumber;
		this.fjjcjName = fjjcjName;
		this.fisrk = fisrk;
		this.frkckId = frkckId;
		this.frkckNumber = frkckNumber;
		this.frkckName = frkckName;
		this.fistjgs = fistjgs;
		this.fsupId = fsupId;
		this.fsupNumber = fsupNumber;
		this.fsupName = fsupName;
		this.ftm = ftm;
		this.fnote = fnote;
	}

	public long getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getParentid() {
		return parentid;
	}

	public void setParentid(int parentid) {
		this.parentid = parentid;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFentryid() {
		return fentryid;
	}

	public void setFentryid(String fentryid) {
		this.fentryid = fentryid;
	}
	public String getFseq() {
		return fseq;
	}

	public void setFseq(String fseq) {
		this.fseq = fseq;
	}
	public String getFgxlzkNo() {
		return fgxlzkNo;
	}

	public void setFgxlzkNo(String fgxlzkNo) {
		this.fgxlzkNo = fgxlzkNo;
	}

	public String getFgxlzkSeq() {
		return fgxlzkSeq;
	}

	public void setFgxlzkSeq(String fgxlzkSeq) {
		this.fgxlzkSeq = fgxlzkSeq;
	}

	public String getFgxlzkId() {
		return fgxlzkId;
	}

	public void setFgxlzkId(String fgxlzkId) {
		this.fgxlzkId = fgxlzkId;
	}

	public String getFgxlzkentryId() {
		return fgxlzkentryId;
	}

	public void setFgxlzkentryId(String fgxlzkentryId) {
		this.fgxlzkentryId = fgxlzkentryId;
	}

	public String getFscddNo() {
		return fscddNo;
	}

	public void setFscddNo(String fscddNo) {
		this.fscddNo = fscddNo;
	}

	public String getFscddSeq() {
		return fscddSeq;
	}

	public void setFscddSeq(String fscddSeq) {
		this.fscddSeq = fscddSeq;
	}

	public String getFscddId() {
		return fscddId;
	}

	public void setFscddId(String fscddId) {
		this.fscddId = fscddId;
	}

	public String getFscddentryId() {
		return fscddentryId;
	}

	public void setFscddentryId(String fscddentryId) {
		this.fscddentryId = fscddentryId;
	}

	public String getFmatId() {
		return fmatId;
	}

	public void setFmatId(String fmatId) {
		this.fmatId = fmatId;
	}

	public String getFmatNumber() {
		return fmatNumber;
	}

	public void setFmatNumber(String fmatNumber) {
		this.fmatNumber = fmatNumber;
	}

	public String getFmatName() {
		return fmatName;
	}

	public void setFmatName(String fmatName) {
		this.fmatName = fmatName;
	}

	public String getFmatModel() {
		return fmatModel;
	}

	public void setFmatModel(String fmatModel) {
		this.fmatModel = fmatModel;
	}

	public String getFclxx() {
		return fclxx;
	}

	public void setFclxx(String fclxx) {
		this.fclxx = fclxx;
	}

	public String getFjgxx() {
		return fjgxx;
	}

	public void setFjgxx(String fjgxx) {
		this.fjgxx = fjgxx;
	}

	public String getFgxId() {
		return fgxId;
	}

	public void setFgxId(String fgxId) {
		this.fgxId = fgxId;
	}

	public String getFgxNumber() {
		return fgxNumber;
	}

	public void setFgxNumber(String fgxNumber) {
		this.fgxNumber = fgxNumber;
	}

	public String getFgxName() {
		return fgxName;
	}

	public void setFgxName(String fgxName) {
		this.fgxName = fgxName;
	}

	public BigDecimal getFqty() {
		return fqty;
	}

	public void setFqty(BigDecimal fqty) {
		this.fqty = fqty;
	}

	public String getFisjj() {
		return fisjj;
	}

	public void setFisjj(String fisjj) {
		this.fisjj = fisjj;
	}

	public String getFjjcjId() {
		return fjjcjId;
	}

	public void setFjjcjId(String fjjcjId) {
		this.fjjcjId = fjjcjId;
	}

	public String getFjjcjNumber() {
		return fjjcjNumber;
	}

	public void setFjjcjNumber(String fjjcjNumber) {
		this.fjjcjNumber = fjjcjNumber;
	}

	public String getFjjcjName() {
		return fjjcjName;
	}

	public void setFjjcjName(String fjjcjName) {
		this.fjjcjName = fjjcjName;
	}

	public String getFisrk() {
		return fisrk;
	}

	public void setFisrk(String fisrk) {
		this.fisrk = fisrk;
	}

	public String getFrkckId() {
		return frkckId;
	}

	public void setFrkckId(String frkckId) {
		this.frkckId = frkckId;
	}

	public String getFrkckNumber() {
		return frkckNumber;
	}

	public void setFrkckNumber(String frkckNumber) {
		this.frkckNumber = frkckNumber;
	}

	public String getFrkckName() {
		return frkckName;
	}

	public void setFrkckName(String frkckName) {
		this.frkckName = frkckName;
	}

	public String getFistjgs() {
		return fistjgs;
	}

	public void setFistjgs(String fistjgs) {
		this.fistjgs = fistjgs;
	}

	public String getFsupId() {
		return fsupId;
	}

	public void setFsupId(String fsupId) {
		this.fsupId = fsupId;
	}

	public String getFsupNumber() {
		return fsupNumber;
	}

	public void setFsupNumber(String fsupNumber) {
		this.fsupNumber = fsupNumber;
	}

	public String getFsupName() {
		return fsupName;
	}

	public void setFsupName(String fsupName) {
		this.fsupName = fsupName;
	}

	public String getFtm() {
		return ftm;
	}

	public void setFtm(String ftm) {
		this.ftm = ftm;
	}

	public String getFnote() {
		return fnote;
	}

	public void setFnote(String fnote) {
		this.fnote = fnote;
	}

	

	
	
	@Override  
    public Object clone() {  
		JrPdaGxpgbillentry obj = null;  
        try{  
        	obj = (JrPdaGxpgbillentry)super.clone();  
        }catch(CloneNotSupportedException e) {  
            e.printStackTrace();  
        }  
        return obj;  
    }  
}
