package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * JrManufactureRecBill generated by hbm2java
 */

public class JrPdaCpbzdjbill implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String fid;
	private String fbillNo;
	private Date fdate;
	private String fmatId;
	private String fmatNumber;
	private String fmatName;
	private String fmatModel;
	private String flot;
	private String fzjs;
	private String fxs;
	private String fzxsl;
	private String fscddId;
	private String fscddNo;
	private String fscddSeq;
	private String fscddentryId;
	private String fdeptId;
	private String fdeptNumber;
	private String fdeptName;


	public JrPdaCpbzdjbill() {
	}


	public JrPdaCpbzdjbill(String fid, String fbillNo, Date fdate,
			String fmatId, String fmatNumber, String fmatName,
			String fmatModel, String flot, String fzjs, String fxs,
			String fzxsl, String fscddId, String fscddNo, String fscddSeq,
			String fscddentryId, String fdeptId, String fdeptNumber,
			String fdeptName) {
		super();
		this.fid = fid;
		this.fbillNo = fbillNo;
		this.fdate = fdate;
		this.fmatId = fmatId;
		this.fmatNumber = fmatNumber;
		this.fmatName = fmatName;
		this.fmatModel = fmatModel;
		this.flot = flot;
		this.fzjs = fzjs;
		this.fxs = fxs;
		this.fzxsl = fzxsl;
		this.fscddId = fscddId;
		this.fscddNo = fscddNo;
		this.fscddSeq = fscddSeq;
		this.fscddentryId = fscddentryId;
		this.fdeptId = fdeptId;
		this.fdeptNumber = fdeptNumber;
		this.fdeptName = fdeptName;
	}


	public String getFid() {
		return fid;
	}


	public void setFid(String fid) {
		this.fid = fid;
	}


	public String getFbillNo() {
		return fbillNo;
	}


	public void setFbillNo(String fbillNo) {
		this.fbillNo = fbillNo;
	}


	public Date getFdate() {
		return fdate;
	}


	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}


	public String getFmatId() {
		return fmatId;
	}


	public void setFmatId(String fmatId) {
		this.fmatId = fmatId;
	}


	public String getFmatNumber() {
		return fmatNumber;
	}


	public void setFmatNumber(String fmatNumber) {
		this.fmatNumber = fmatNumber;
	}


	public String getFmatName() {
		return fmatName;
	}


	public void setFmatName(String fmatName) {
		this.fmatName = fmatName;
	}


	public String getFmatModel() {
		return fmatModel;
	}


	public void setFmatModel(String fmatModel) {
		this.fmatModel = fmatModel;
	}


	public String getFlot() {
		return flot;
	}


	public void setFlot(String flot) {
		this.flot = flot;
	}


	public String getFzjs() {
		return fzjs;
	}


	public void setFzjs(String fzjs) {
		this.fzjs = fzjs;
	}


	public String getFxs() {
		return fxs;
	}


	public void setFxs(String fxs) {
		this.fxs = fxs;
	}


	public String getFzxsl() {
		return fzxsl;
	}


	public void setFzxsl(String fzxsl) {
		this.fzxsl = fzxsl;
	}


	public String getFscddId() {
		return fscddId;
	}


	public void setFscddId(String fscddId) {
		this.fscddId = fscddId;
	}


	public String getFscddNo() {
		return fscddNo;
	}


	public void setFscddNo(String fscddNo) {
		this.fscddNo = fscddNo;
	}


	public String getFscddSeq() {
		return fscddSeq;
	}


	public void setFscddSeq(String fscddSeq) {
		this.fscddSeq = fscddSeq;
	}


	public String getFscddentryId() {
		return fscddentryId;
	}


	public void setFscddentryId(String fscddentryId) {
		this.fscddentryId = fscddentryId;
	}


	public String getFdeptId() {
		return fdeptId;
	}


	public void setFdeptId(String fdeptId) {
		this.fdeptId = fdeptId;
	}


	public String getFdeptNumber() {
		return fdeptNumber;
	}


	public void setFdeptNumber(String fdeptNumber) {
		this.fdeptNumber = fdeptNumber;
	}


	public String getFdeptName() {
		return fdeptName;
	}


	public void setFdeptName(String fdeptName) {
		this.fdeptName = fdeptName;
	}

	
}
