package com.jxjr.m.entity;

// Generated 2017-3-22 20:54:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * JrManufactureRecBill generated by hbm2java
 */

public class JrPdaGxpgbill implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String fid;
	private String fbillNo;
	private String fdeptId;
	private String fdeptNumber;
	private String fdeptName;
	private String fbzId;
	private String fbzNumber;
	private String fbzName;
	private String fempxx;
	private String ftype;
	private String fmemo;
	private Date fdate;

	
	public JrPdaGxpgbill(int id, String fid, String fbillno,
			String fdeptid, String fdeptNumber, String fdeptName,
			String fbzId, String fbzNumber,
			 String fbzName,
			String fempxx, String ftype,
			String fmemo,Date fdate) {
		this.id = id;
		this.fid = fid;
		this.fbillNo = fbillno;
		this.fdeptId = fdeptid;
		this.fdeptNumber = fdeptNumber;
		this.fdeptName = fdeptName;
		this.fbzId = fbzId;
		this.fbzNumber = fbzNumber;
		this.fbzName = fbzName;
		this.fempxx = fempxx;
		this.ftype = ftype;
		this.fmemo = fmemo;
		this.fdate=fdate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}


	public String getFbillNo() {
		return fbillNo;
	}

	public void setFbillNo(String fbillNo) {
		this.fbillNo = fbillNo;
	}

	public String getFdeptId() {
		return fdeptId;
	}

	public void setFdeptId(String fdeptId) {
		this.fdeptId = fdeptId;
	}

	public String getFdeptNumber() {
		return fdeptNumber;
	}

	public void setFdeptNumber(String fdeptNumber) {
		this.fdeptNumber = fdeptNumber;
	}

	public String getFdeptName() {
		return fdeptName;
	}

	public void setFdeptName(String fdeptName) {
		this.fdeptName = fdeptName;
	}

	public String getFbzId() {
		return fbzId;
	}

	public void setFbzId(String fbzId) {
		this.fbzId = fbzId;
	}

	public String getFbzNumber() {
		return fbzNumber;
	}

	public void setFbzNumber(String fbzNumber) {
		this.fbzNumber = fbzNumber;
	}

	public String getFbzName() {
		return fbzName;
	}

	public void setFbzName(String fbzName) {
		this.fbzName = fbzName;
	}

	public String getFempxx() {
		return fempxx;
	}

	public void setFempxx(String fempxx) {
		this.fempxx = fempxx;
	}

	public String getFtype() {
		return ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public String getFmemo() {
		return fmemo;
	}

	public void setFmemo(String fmemo) {
		this.fmemo = fmemo;
	}

	public Date getFdate() {
		return fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	public JrPdaGxpgbill() {
	}

	public JrPdaGxpgbill(int id) {
		this.id = id;
	}

	
	
	
}
