package com.jxjr.m.pojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BASE_INFO_OBJECT_POJO.
 */
public class BaseInfoObjectPOJO {

    private Long id;
    private String fItemClass;
    private String fItemID;
    private String fNumber;
    private String fName;
    private String fParam;
    private String forgid;

    public BaseInfoObjectPOJO() {
    }

    public BaseInfoObjectPOJO(Long id) {
        this.id = id;
    }

    public BaseInfoObjectPOJO(Long id, String fItemClass, String fItemID, String fNumber, String fName, String fParam, String forgid) {
        this.id = id;
        this.fItemClass = fItemClass;
        this.fItemID = fItemID;
        this.fNumber = fNumber;
        this.fName = fName;
        this.fParam = fParam;
        this.forgid = forgid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    
    public String getFItemClass() {
        return fItemClass;
    }

    public void setFItemClass(String fItemClass) {
        this.fItemClass = fItemClass;
    }

    public String getFItemID() {
        return fItemID;
    }

    public void setFItemID(String fItemID) {
        this.fItemID = fItemID;
    }

    public String getFNumber() {
        return fNumber;
    }

    public void setFNumber(String fNumber) {
        this.fNumber = fNumber;
    }

    public String getFName() {
        return fName;
    }

    public void setFName(String fName) {
        this.fName = fName;
    }

    public String getFParam() {
        return fParam;
    }

    public void setFParam(String fParam) {
        this.fParam = fParam;
    }

    public String getForgid() {
        return forgid;
    }

    public void setForgid(String forgid) {
        this.forgid = forgid;
    }

}
