package com.jxjr.m.pojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BILL_CODE_POJO".
 */
public class BillCodePOJO {

    private Long id;
    private String billHead;
    private String billEntry;

    public BillCodePOJO() {
    }

    public BillCodePOJO(Long id) {
        this.id = id;
    }

    public BillCodePOJO(Long id, String billHead, String billEntry) {
        this.id = id;
        this.billHead = billHead;
        this.billEntry = billEntry;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillHead() {
        return billHead;
    }

    public void setBillHead(String billHead) {
        this.billHead = billHead;
    }

    public String getBillEntry() {
        return billEntry;
    }

    public void setBillEntry(String billEntry) {
        this.billEntry = billEntry;
    }

}
