package com.jxjr.m.pojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG_INFO_POJO.
 */
public class LogInfoPOJO {

    private Long id;
    private String fDateTime;
    private String fMod;
    private Integer fUserID;
    private String fUserNumber;
    private String fUserName;
    private Integer fGzID;
    private String fGzNumber;
    private String fGzName;
    private Integer fBmID;
    private String fBmNumber;
    private String fBmName;
    private String fDescription;
    private String deviceID;

    public LogInfoPOJO() {
    }

    public LogInfoPOJO(Long id) {
        this.id = id;
    }

    public LogInfoPOJO(Long id, String fDateTime, String fMod, Integer fUserID, String fUserNumber, String fUserName, Integer fGzID, String fGzNumber, String fGzName, Integer fBmID, String fBmNumber, String fBmName, String fDescription, String deviceID) {
        this.id = id;
        this.fDateTime = fDateTime;
        this.fMod = fMod;
        this.fUserID = fUserID;
        this.fUserNumber = fUserNumber;
        this.fUserName = fUserName;
        this.fGzID = fGzID;
        this.fGzNumber = fGzNumber;
        this.fGzName = fGzName;
        this.fBmID = fBmID;
        this.fBmNumber = fBmNumber;
        this.fBmName = fBmName;
        this.fDescription = fDescription;
        this.deviceID = deviceID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFDateTime() {
        return fDateTime;
    }

    public void setFDateTime(String fDateTime) {
        this.fDateTime = fDateTime;
    }

    public String getFMod() {
        return fMod;
    }

    public void setFMod(String fMod) {
        this.fMod = fMod;
    }

    public Integer getFUserID() {
        return fUserID;
    }

    public void setFUserID(Integer fUserID) {
        this.fUserID = fUserID;
    }

    public String getFUserNumber() {
        return fUserNumber;
    }

    public void setFUserNumber(String fUserNumber) {
        this.fUserNumber = fUserNumber;
    }

    public String getFUserName() {
        return fUserName;
    }

    public void setFUserName(String fUserName) {
        this.fUserName = fUserName;
    }

    public Integer getFGzID() {
        return fGzID;
    }

    public void setFGzID(Integer fGzID) {
        this.fGzID = fGzID;
    }

    public String getFGzNumber() {
        return fGzNumber;
    }

    public void setFGzNumber(String fGzNumber) {
        this.fGzNumber = fGzNumber;
    }

    public String getFGzName() {
        return fGzName;
    }

    public void setFGzName(String fGzName) {
        this.fGzName = fGzName;
    }

    public Integer getFBmID() {
        return fBmID;
    }

    public void setFBmID(Integer fBmID) {
        this.fBmID = fBmID;
    }

    public String getFBmNumber() {
        return fBmNumber;
    }

    public void setFBmNumber(String fBmNumber) {
        this.fBmNumber = fBmNumber;
    }

    public String getFBmName() {
        return fBmName;
    }

    public void setFBmName(String fBmName) {
        this.fBmName = fBmName;
    }

    public String getFDescription() {
        return fDescription;
    }

    public void setFDescription(String fDescription) {
        this.fDescription = fDescription;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

}
